# Generated by Django 3.2.7 on 2023-04-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('map_id', models.URLField()),
                ('additional_Type', models.URLField()),
                ('medical_Specialty', models.CharField(max_length=255, null=True)),
                ('payment_Accepted', models.CharField(max_length=255, null=True)),
                ('hasMap', models.CharField(max_length=1000, null=True)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('isAcceptingNewPatients', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=255)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('AlternateName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('disambiguatingDescription', models.TextField()),
                ('foundingDate', models.CharField(max_length=255)),
                ('SameAs', models.TextField()),
                ('publisher_type', models.CharField(max_length=255)),
                ('publisher_name', models.CharField(max_length=100)),
                ('website_id', models.CharField(max_length=100)),
                ('website_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KnowsLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_id', models.URLField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=255)),
                ('timming', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.ImageField(upload_to='images/')),
                ('creator', models.CharField(max_length=255)),
                ('contentLocation', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
        migrations.CreateModel(
            name='Haspart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('haspart_id', models.URLField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.URLField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('contactType', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='curreny_Accepted',
            field=models.ManyToManyField(to='main.Currency'),
        ),
        migrations.AddField(
            model_name='business',
            name='knows_language',
            field=models.ManyToManyField(to='main.KnowsLanguage'),
        ),
        migrations.CreateModel(
            name='AvailableService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sameAs', models.URLField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
        migrations.CreateModel(
            name='AreaServed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('area_id', models.URLField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('addressRegion', models.CharField(max_length=255)),
                ('addressCountry', models.CharField(max_length=255)),
                ('streetAddress', models.CharField(max_length=500)),
                ('addressLocality', models.CharField(max_length=500)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.business')),
            ],
        ),
    ]
