# Generated by Django 3.2.7 on 2023-04-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='publisher_id',
            new_name='p_id',
        ),
    ]
