# Generated by Django 3.2.7 on 2023-04-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_publisher_id_publisher_p_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='publisher_name',
            new_name='pub_name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='publisher_type',
            new_name='pub_type',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='website_url',
            new_name='pub_url',
        ),
        migrations.RenameField(
            model_name='haspart',
            old_name='type',
            new_name='h_type',
        ),
        migrations.AddField(
            model_name='business',
            name='publisher_id',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='isAcceptingNewPatients',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
