# Generated by Django 4.1 on 2023-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_knowslanguage_website_business_alternatename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='medicalSpecialty',
            new_name='medical_Specialty',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='paymentAccepted',
            new_name='payment_Accepted',
        ),
        migrations.AlterField(
            model_name='business',
            name='isAcceptingNewPatients',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=255),
        ),
    ]
