# Generated by Django 3.2.7 on 2023-04-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230413_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='p_id',
            new_name='publisher_id',
        ),
    ]
