# Generated by Django 3.2.7 on 2023-04-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230413_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='pub_name',
            new_name='publisher_name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='pub_type',
            new_name='publisher_type',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='pub_url',
            new_name='website_url',
        ),
        migrations.AlterField(
            model_name='business',
            name='hasMap',
            field=models.URLField(default='https://lcmgcf.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='isAcceptingNewPatients',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='website_id',
            field=models.URLField(),
        ),
    ]
